### ISSUE TITLE
[feature] allow setting a base_url for app_backend, app_frontend

### ISSUE THREAD

**Issue by johoja12** [vanlittle/VNF-Onboarding#12]
allow setting a base_url for app_backend, app_frontend

I.e) localhost:5000**/api/**
      localhost:3000**/ui/**

**Comment by vanlittle** [comment]
added bug tag

**Comment by johoja12** [comment]
Currently in the vnf onboarding tool the app uses 2 ports one for frontend, and one for backend

1 - localhost: 3000, and localhost:5000

In a production enviornment we are using nginx to serve the http requests to clients , ideally we'dl like to only expose 1 port on the firewall for example fort 443 for HTTPs or port 80 for HTTP.

This can be done by using nginx proxypass, however the url namespace for the two ports is the same i.e) '/'

In nginx you specify a location to proxypass so for example

<< this is not exact nginx configuration, just an example  >>

location '/'
   proxypass http://localhost:3000

but since the location for both the frontend, and backend is '/' we can't proxypass  -- having a configurable base url i.e) make the backend localhost:5000/api/

we can do a the following then 

location '/api/'
 proxypass http://localhost:5000/api

**Comment by nandkumarj** [comment]
With this fix , backend service will be running on 'http://localhost:5000/backend'

**Comment by nandkumarj** [comment]
Changes for this are checked in. Closing this issue.
