### ISSUE TITLE
Rift with Openstack allows custom flavors even when one is selected

### ISSUE THREAD

**Issue by vanlittle** [vanlittle/VNF-Onboarding#18]
In the flavors dropdown, the vCPU, RAM and Disk options should be greyed out unless 'Custom' flavor is selected.  

Right now, those options are available even if you select one of the existing flavors

**Comment by nandkumarj** [comment]
This is working for other orchestrators. This seems to be issue with only Rift.io. vCPU,RAM and Disk inputs should be greyed out when existing flavor is selected.  For Custom Flavor only these inputs should be enabled.
