### ISSUE TITLE
RIFT with Openstack EPA configurations are skipped

### ISSUE THREAD

**Issue by vanlittle** [vanlittle/VNF-Onboarding#19]
Enable EPA configurations for Rift.ware orchestrator with openstack

**Comment by nandkumarj** [comment]
This issue will be covered in Issue #23 and Issue#29. In current implementation , Rift.io does not support EPA parameters . Riftio blueprint needs to have placeholders for Guest EPA parameters supported by VNF Onboarding tool. This is being followed with Rift io. Along with that , UI also needs changes to have EPA Parameters page for Rift.io and capture user inputs.

**Comment by vanlittle** [comment]
This issue was moved to vmware/bellhop#29
