### ISSUE TITLE
File names in git that are going to be user modified should end with ".sample"

### ISSUE THREAD

**Issue by nandkumarj** [vanlittle/VNF-Onboarding#22]
For example database.ini.sample during configuration then you copy that file to database.ini and it won't conflict if there are changes in git.

**Comment by nandkumarj** [comment]
Right now there are two files which needs to be modified by user after deployment
1. database.ini
2. git_config.sh

**Comment by amolbjadhav** [comment]
The issue is fixed.

**Comment by nandkumarj** [comment]
Closing this.
