### ISSUE TITLE
custom flavor doesn"t work

### ISSUE THREAD

**Issue by kdunaev-a10** [vanlittle/VNF-Onboarding#23]
if i choose custom flavor it is inactive.

**Comment by johoja12** [comment]
:label bug

**Comment by nandkumarj** [comment]
Add more details of the problem. Like what is inactive? Combination of VIM + Orchestrator  where this behaviour is observed.

**Comment by kdunaev-a10** [comment]
Hi, 

it was quick and dirty bug report, I'm really sorry for that. 
Some details to the problem, which is probably not the bug as such, but more the way of configuration. 
If I choose the "vCloud Director", we can't specify the Flavor at all, which make sense and consistent over all formats.

If we choose the OpenStack we have some different possibilities, which may lead to confusion, because they are not fully consistent and not obvious,  especially for inexperienced users (who will actually use this tool in the first place):
- Tosca 1.1 and Cloudify  work fully expected, to my view. We can choose flavor name, or we can choose "custom", specify the name and set the params for RAM and CPU and Disk.
- in RiftIO and OSM3, it doesn't matter if choose the flavor-name or Custom, we still able to setup the configure the params for CPU, disk and RAM. if we choose Custom, we can't specify the name.

Also when I choose RiftIO and OSM3 template and continue to EPA page, it does actually appear and I seethe previous page (it shows me the NIC configuration), if I click continue, I get the next step.
If I click "back", again, the page shows me the previous step, but not EPA.

**Comment by nandkumarj** [comment]
Thanks for details.  Yes for Riftio there is a problem with flavor and EPA parameters . For OSM , flavor is not supported. Also EPA parameters  retain their values across page navigation.

**Comment by nandkumarj** [comment]
1. With Current implementation Rift.io does not support EPA parameters. For Guest EPA Parameters that tool supports there should be placeholders  in the blueprint. This is being followed up with Riftio. From UI side as well things need to change so that EPA parameters page is part of  rift.io blueprint generation  flow and user inputs are captured. 
2. For Rift.io custom flavor, CPU,RAM and Disk inputs should be disabled.

**Comment by vanlittle** [comment]
This issue was moved to vmware/bellhop#27
