### ISSUE TITLE
[BUG] empty nic definition is allowed

### ISSUE THREAD

**Issue by ssasso** [vanlittle/VNF-Onboarding#25]
empty nic definition should not be allowed (validation not working) when clicking "Next"

**Comment by nandkumarj** [comment]
This behaviour is expected. Currently tool does not validate any field.

**Comment by nandkumarj** [comment]
Rather , this is a known limitation

**Comment by nandkumarj** [comment]
It will be covered under validation of fields story.

**Comment by amolbjadhav** [comment]
The issue is fixed.
