### ISSUE TITLE
[BUG] Chrome - Upload VNF cycles back to first screen

### ISSUE THREAD

**Issue by captainpacket** [vanlittle/VNF-Onboarding#26]
In Chrome, when you select to upload a VNF the screen cycles back to the intro screen.

**Comment by nandkumarj** [comment]
Please update issue with steps to reproduce. Provide Browser Version.

**Comment by nandkumarj** [comment]
Only scenario where this can happen is when user clicks "Create New" button on the "Generate" page. In that case this would be "Functions As Designed" .  "Create New" Button appears on the same place as "Continue" button appears on previous pages. So there is a chance that user might have pressed "Create New" button believing that its a "Continue" button.  If thats what has happened, I don't think we need to do anything to preclude such user errors.  With no details coming from reporter I am inclined to believe that its a case of user error.

**Comment by nandkumarj** [comment]
Confirmed from Reporter's response that it was an "user error". So closing this issue.
