### ISSUE TITLE
Upload Scripts UI screen's 'Choose Files' option to populate the input box with uploaded file's name

### ISSUE THREAD

**Issue by sin-ak** [vanlittle/VNF-Onboarding#38]
In the Upload Scripts UI screen, when we select 'Choose Files' and select a file from our local machine, it should populate the blank input box with the name of the file automatically, so that the user doesn't have to enter it manually and there are no typos while entering the name.
![screen shot 2018-03-21 at 18 23 05](https://user-images.githubusercontent.com/13421773/37746075-9cb3216a-2d35-11e8-8dc1-374ed9ddad95.png)

**Comment by vanlittle** [comment]
This issue was moved to vmware/bellhop#23
