### ISSUE TITLE
Mutli-VDU Support 

### ISSUE THREAD

**Issue by nandkumarj** [vanlittle/VNF-Onboarding#54]
Currently VNF Onboarding tool creates a VNFD with a single VDU. VNF ONboarding tool should be able to create VNFD with multiple VDU/VMs.

**Comment by amolbjadhav** [comment]
Cloudify templates for MultiVDU support are added.

**Comment by amolbjadhav** [comment]
Custom flavor file supporting multiple vdu is added

**Comment by nandkumarj** [comment]
This issue was for VNF Onboarding MultiVDU feature.  MultiVDU Support for OSM And Cloudify orchestrators was addressed under this one. Closing this.
