### ISSUE TITLE
Validation of parameters in VNF Onboarding tool

### ISSUE THREAD

**Issue by amolbjadhav** [vanlittle/VNF-Onboarding#74]
1. No of VMs must be numeric and have range of 1-20
2. VNF name must not have space and special characters.
3. Management network must not be blank
4. Additional networks must be numeric and between 0-20
5. Network interface must not be blank
6. Image name must not be blank
7. Disk must be numeric. 
8. Network interface must not be blank on NIC definition page.
9. Number of Numa nodes must be numeric.
10. If the scripts are uploaded then script name should not be blank.
11. Login Page and Sign Up page validation
     a. Blank user name should not get accepted during sign up
     b. 'Password' and 'Confirm Password' should be same. If they are not same, an error message should appear on screen 
     c. If the email is not delivered, the sign up should be successful with warning message 
     d. If the email is left blank then user registration should fail with appropriate error message.
     e. user name and password should have some restrictions.

**Comment by harshwardhas** [comment]
If the scripts are uploaded then script name should not be blank and If the email is not delivered, the sign up should be successful with warning message.
Above issues will be tracked under other issue number.

**Comment by nandkumarj** [comment]
This has been fixed. So closing this.
