### ISSUE TITLE
Not letting me to sign up and log in

### ISSUE THREAD

**Issue by shashi-rks** [vanlittle/VNF-Onboarding#76]
I downloaded code from git hub and built it. As I do http://localhost:3000/, login page appears and I try to sign up. Whatever credentials I provide on sign up, they are simple rejected with reason "User Registration Failed. Username or Emailid already exists."

Same issue I am seeing when I try to login via on-line portal http://vnfonboarding.com

**Comment by varadep** [comment]
Can you try login with credentials you provided? (although it complains about user exist) it seems to be due to error while sending email.
I just logged in to http://vnfonboarding.com and able to get it.

**Comment by shashi-rks** [comment]
No It's not working for me. Whatever I try, it is rejected with reason "User Registration Failed. Username or Emailid already exists."

**Comment by varadep** [comment]
May be not relevant but I just tried this on Safari and chrome browser on http://vnfonboarding.com just created dummy user and it was successful, also logged in using new user successfully.

Are you trying this on http://vnfonboarding.com or the code you cloned?

**Comment by shashi-rks** [comment]
Both are not working for me, I tried http://vnfonboarding.com and the code I cloned on firefox and chrome. But every time its not letting me to log in. Throwing error "User Registration Failed. Username or Emailid already exists." on signup and "invalid user name or password" when I try to simply log in.

**Comment by shashi-rks** [comment]
I am sorry to bother you. It was LAN issue at my end.
