### ISSUE TITLE
When we traverse back and forth in GUI, the old values gets retained in summary page.

### ISSUE THREAD

**Issue by amolbjadhav** [vanlittle/VNF-Onboarding#80]
Steps to reproduce:
1. Select Vim and Orchestrator  combination 
2. Select additional networks e..g 5 and add the details in "Network Configurations"
3. Add other details and proceed till the summary page.
4. Traverse back and change the Additional networks to some less numbers e.g. 2  or 
Reduce the the Number of NICs for VM in Network Configuration page.
4. Traverse forth to summary page, the old values filled previously would get retained and would reflect in blueprint as well.

This is known limitation due to present code architecture and would need modifications in the static structures which are storing these values.

**Comment by vanlittle** [comment]
This issue was moved to vmware/bellhop#9
