### ISSUE TITLE
Creating new network with cloudify + Openstack

### ISSUE THREAD

**Issue by nandkumarj** [vanlittle/VNF-Onboarding#83]
For Cloudify , network names that are captured  need to exist in VIM.  With this enhancement, this restriction won't be there and  it would be possible to create a new network using cloudify.

**Comment by nandkumarj** [comment]
Effort involved for this enhancement is significant. So  for better tracking bifurcating this into issue per  platform.

**Comment by amolbjadhav** [comment]
Checked in the code for the feature "Creating new network with cloudify + Openstack #83"

**Comment by vanlittle** [comment]
This issue was moved to vmware/bellhop#6
